"""empty message

Revision ID: 0c2eb76f45d7
Revises: 62ef6c119cf6
Create Date: 2021-08-12 08:25:48.137801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2eb76f45d7'
down_revision = '62ef6c119cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
