"""empty message

Revision ID: 49254b10e950
Revises: 776e37d93e48
Create Date: 2021-08-14 07:13:14.743495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49254b10e950'
down_revision = '776e37d93e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_feed_entry_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'entries', ['feed_entry_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('entries_feed_id_fkey', 'entries', type_='foreignkey')
    op.create_foreign_key(None, 'entries', 'feeds', ['feed_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_feed_user_id_fkey', 'user_feed', type_='foreignkey')
    op.drop_constraint('user_feed_feed_id_fkey', 'user_feed', type_='foreignkey')
    op.create_foreign_key(None, 'user_feed', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_feed', 'feeds', ['feed_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_feed_entry_states_feed_entry_id_fkey', 'user_feed_entry_states', type_='foreignkey')
    op.drop_constraint('user_feed_entry_states_user_id_fkey', 'user_feed_entry_states', type_='foreignkey')
    op.create_foreign_key(None, 'user_feed_entry_states', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_feed_entry_states', 'entries', ['feed_entry_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_feed_states_user_id_fkey', 'user_feed_states', type_='foreignkey')
    op.drop_constraint('user_feed_states_feed_id_fkey', 'user_feed_states', type_='foreignkey')
    op.create_foreign_key(None, 'user_feed_states', 'feeds', ['feed_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_feed_states', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_feed_states', type_='foreignkey')
    op.drop_constraint(None, 'user_feed_states', type_='foreignkey')
    op.create_foreign_key('user_feed_states_feed_id_fkey', 'user_feed_states', 'feeds', ['feed_id'], ['id'])
    op.create_foreign_key('user_feed_states_user_id_fkey', 'user_feed_states', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_feed_entry_states', type_='foreignkey')
    op.drop_constraint(None, 'user_feed_entry_states', type_='foreignkey')
    op.create_foreign_key('user_feed_entry_states_user_id_fkey', 'user_feed_entry_states', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_feed_entry_states_feed_entry_id_fkey', 'user_feed_entry_states', 'entries', ['feed_entry_id'], ['id'])
    op.drop_constraint(None, 'user_feed', type_='foreignkey')
    op.drop_constraint(None, 'user_feed', type_='foreignkey')
    op.create_foreign_key('user_feed_feed_id_fkey', 'user_feed', 'feeds', ['feed_id'], ['id'])
    op.create_foreign_key('user_feed_user_id_fkey', 'user_feed', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.create_foreign_key('entries_feed_id_fkey', 'entries', 'feeds', ['feed_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key('comments_feed_entry_id_fkey', 'comments', 'entries', ['feed_entry_id'], ['id'])
    # ### end Alembic commands ###
