"""empty message

Revision ID: 62ef6c119cf6
Revises: f42c1ebe6b16
Create Date: 2021-08-12 08:25:00.013805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ef6c119cf6'
down_revision = 'f42c1ebe6b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
