"""empty message

Revision ID: 776e37d93e48
Revises: f34759d1ea72
Create Date: 2021-08-14 07:07:18.529398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776e37d93e48'
down_revision = 'f34759d1ea72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
