"""empty message

Revision ID: bcf4e026cf2b
Revises: d3aa17e69fb5
Create Date: 2021-08-13 11:35:58.217465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf4e026cf2b'
down_revision = 'd3aa17e69fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
