"""empty message

Revision ID: d3aa17e69fb5
Revises: 0c2eb76f45d7
Create Date: 2021-08-13 09:36:57.380604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3aa17e69fb5'
down_revision = '0c2eb76f45d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_read_states_id', table_name='read_states')
    op.drop_table('read_states')
    op.drop_index('ix_favorites_id', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index('ix_feeds_unique_name', table_name='feeds')
    op.drop_constraint('name_url_unique', 'feeds', type_='unique')
    op.create_index(op.f('ix_feeds_url'), 'feeds', ['url'], unique=True)
    op.drop_column('feeds', 'unique_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('unique_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_feeds_url'), table_name='feeds')
    op.create_unique_constraint('name_url_unique', 'feeds', ['unique_name', 'url'])
    op.create_index('ix_feeds_unique_name', 'feeds', ['unique_name'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feed_entry_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_favorite', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feed_entry_id'], ['entries.id'], name='favorites_feed_entry_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey'),
    sa.UniqueConstraint('user_id', 'feed_entry_id', name='user_entry_favorite_unique')
    )
    op.create_index('ix_favorites_id', 'favorites', ['id'], unique=False)
    op.create_table('read_states',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feed_entry_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feed_entry_id'], ['entries.id'], name='read_states_feed_entry_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='read_states_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='read_states_pkey'),
    sa.UniqueConstraint('user_id', 'feed_entry_id', name='user_entry_read_unique')
    )
    op.create_index('ix_read_states_id', 'read_states', ['id'], unique=False)
    # ### end Alembic commands ###
