"""empty message

Revision ID: e97cc8999421
Revises: 
Create Date: 2021-08-11 08:47:53.109094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97cc8999421'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_feed_entry_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'entries', ['feed_entry_id'], ['id'])
    op.add_column('entries', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('read_states_feed_entry_id_fkey', 'read_states', type_='foreignkey')
    op.create_foreign_key(None, 'read_states', 'entries', ['feed_entry_id'], ['id'])
    op.drop_column('users', 'points')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'read_states', type_='foreignkey')
    op.create_foreign_key('read_states_feed_entry_id_fkey', 'read_states', 'feeds', ['feed_entry_id'], ['id'])
    op.drop_column('entries', 'published_at')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_feed_entry_id_fkey', 'comments', 'feeds', ['feed_entry_id'], ['id'])
    # ### end Alembic commands ###
