"""empty message

Revision ID: f34759d1ea72
Revises: bcf4e026cf2b
Create Date: 2021-08-14 07:04:44.327654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34759d1ea72'
down_revision = 'bcf4e026cf2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
