"""empty message

Revision ID: f42c1ebe6b16
Revises: e97cc8999421
Create Date: 2021-08-12 08:24:01.567021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42c1ebe6b16'
down_revision = 'e97cc8999421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
